steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "--pull", "--tag", "${_IMAGE}", "."]

images:
  - "${_IMAGE}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/example-project/artificial-analyzer/x-publisher:manual
